### ISSUE TITLE
Fix Scale on Export

### ISSUE THREAD

**Issue by BPLRFE** [marmni/FreeCAD-Kerkythea#1]
Since FreeCAD standard is mm and Kerkythea seems to expect m please correct scale on export or insert option to choose scale.

**Comment by BPLRFE** [comment]
OK, after playing around I found a temporary workaroud

> make part compound or Fusion of parts with same material
> make draft clone of the compounds/fusions
> set scale-factor "x" of draft clone (data tab) to "0,001"
> set scale-factor "y" of draft clone (data tab) to "0,001"
> set scale-factor "z" of draft clone (data tab) to "0,001"
> select clones
> export clones with makro to Kerkythea

**Comment by marmni** [comment]
Hello,
I just received info about Your issue.Problem mentioned by You, is solved from weeks (even months). I have problem with uploading script by git on linux - some weird error appears.

If You want current version, download FreeCAD-PCB workbench (best solution) or please send me message via mail marmni@onetREMOVEIT.eu (delete REMOVEIT) - so I will send to You script.
There is still problem with camera position in script.

Sorry for trouble.

**Comment by BPLRFE** [comment]
Since Scale Problem is fixed you can close Issue.

Thank you.
